name: envio-bn-booster-s2-indexer
description: Envio Binance Booster S2 indexer
#Global contract definitions that must contain all definitions except
#addresses. Now you can share a single handler/abi/event definitions
#for contracts across multiple chains
contracts:
  - name: NodeStakingVault
    abi_file_path: ./abis/node-staking-vault-abi.json
    handler: ./src/NodeStakingVaultEventHandlers.js
    events:
      - event: DelegateAmountIncreased(address indexed user, address indexed node, uint256 amount, uint256 newTotalAmount, uint256 effectiveMultiplier)
      - event: DelegateUnstaked(address indexed user, uint256 amount)
      - event: DelegateUnstakingInitiated(address indexed user, address indexed node, uint256 amount, uint256 cooldownAmount)
      - event: Delegated(address indexed user, address indexed node, uint256 amount, uint256 effectiveMultiplier, uint256 effectiveLockUpPeriod)
      - event: DelegateLockupIncreased(address indexed user, address indexed node, uint256 lockupPeriod, uint256 newEffectiveLockup, uint256 effectiveMultiplier)
rollback_on_reorg: false
networks:
  - id: 97 # BSC
    start_block: 80635312
    contracts:
      - name: NodeStakingVault
        address: "0x52D5109A3a066aA6bf21792F201fC93EE6F8a525"
field_selection:
  transaction_fields:
    - "hash"
    - "transactionIndex"
